---
- name: Deploy all microservices from Nexus
  hosts: microservices
  become: yes

  vars:
    nexus_registry: "34.238.246.157:8082"
    nexus_username: "admin"
    nexus_password: "YassineNexus12**"
    services:
      - configservice
      - counterservice
      - registryservice
      - gatewayservice
    service_ports:
      configservice: 8888
      counterservice: 9000
      registryservice: 8761
      gatewayservice: 8080
    image_tag: "{{ image_tag | default('latest') }}"

  tasks:
    - name: Authenticate to Nexus Docker registry
      shell: |
        echo "{{ nexus_password }}" \
        | docker login {{ nexus_registry }} -u {{ nexus_username }} --password-stdin

    - name: Pull image for each microservice
      shell: docker pull {{ nexus_registry }}/{{ svc }}:{{ image_tag }}
      loop: "{{ services }}"
      loop_control:
        loop_var: svc

    - name: Stop existing container for each microservice
      shell: docker stop {{ svc }} || true
      loop: "{{ services }}"
      loop_control:
        loop_var: svc

    - name: Remove existing container for each microservice
      shell: docker rm {{ svc }} || true
      loop: "{{ services }}"
      loop_control:
        loop_var: svc

    - name: Run container for each microservice
      shell: |
        docker run -d --name {{ svc }} \
          -p {{ service_ports[svc] }}:{{ service_ports[svc] }} \
          {{ nexus_registry }}/{{ svc }}:{{ image_tag }}
      loop: "{{ services }}"
      loop_control:
        loop_var: svc
